### ISSUE TITLE
v0.2 Roadmap

### ISSUE THREAD

**Issue by JeffersonQin** [JeffersonQin/YuzuMarker#3]
v0.2 计划：

- UI
  - [ ] 界面封装成若干个 UserControl
  - [ ] 多 Tab 界面
  - [ ] Settings
  - [ ] 背景区域选择：放大缩小提供 Structuring Element 的设置，例如 Oval / Rect，Kernel 的大小
  - [ ] 背景区域：Peak 计算提供界面配置 minDist, thres, thresAbs（可折叠的那种）
  - [ ] 背景区域：颜色选择 Async
  - [ ] 调用 Photoshop / IPS 等 Backend 服务添加加载页面
- Model
  - [ ] Setting 抽象
